// Copyright (c) 2026 The DealerFOSS contributors.
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Overview: Purpose, File Design, and Engineering
//   SourceHeaderTests — the four-part header rule (doc 08 §5), enforced instead
//   of remembered.
//
//   The rule was applied to all 347 files on 2026-09-04 and then had nothing
//   watching it. By 2026-09-14 the repository had grown to 379 files and the
//   scope register still carried the row as open work "waiting to be
//   scheduled", because the only way to find out whether it was done was to
//   look at every file by hand. Exactly one file had slipped through. One in
//   379 is a good result and an unrepeatable one: the next thirty files are
//   added by somebody who has not read doc 08.
//
//   This walks the working tree rather than asking git, so a file that is not
//   committed yet is still checked. That is the point — the header is meant to
//   be written when the file is, not remembered at commit time.
//
// Usage:
//   dotnet test DealerFOSS.slnx -c Release
//
//   A failure names every offending file and which of the five markers it is
//   missing, so the fix does not need a second run to find.
//
// Coding Instructions:
//   THE FILE COUNT IS AN ASSERTION, NOT A STATISTIC. If the walk cannot find
//   the repository root it enumerates nothing, and a test that checks "none of
//   the zero files I found is wrong" passes forever while guarding nothing.
//   Do not remove the count, and do not lower it to make a run go green.
//
//   THE COPYRIGHT YEAR IS A PATTERN, NOT A CONSTANT. A file written in 2027
//   carries 2027, and hard-coding this year would fail the whole suite on
//   1 January for no reason anybody could act on.
//
//   THE THREE EXCLUSIONS ARE IN doc 08 §5 AND ARE LOAD-BEARING. Migrations are
//   generated and EF overwrites them; .json cannot carry a comment at all; and
//   .html must open with <!doctype html> or the browser drops into quirks mode,
//   so a comment above it would change how the page renders. Excluding a fourth
//   KIND of file is a governance change — amend doc 08 first.
//
//   The skipped DIRECTORIES are a different thing and need no amendment: none
//   of them holds source belonging to this repository. They are build output,
//   git-ignored working areas, or — `.claude/worktrees` — an entirely separate
//   checkout that an agent is working in, whose files are that checkout's
//   problem and would otherwise be reported twice.

using System.Text.RegularExpressions;
using FluentAssertions;
using Xunit;

namespace DealerFOSS.ArchitectureTests;

public sealed class SourceHeaderTests
{
    /// <summary>The extensions doc 08 §5 names, plus .yaml, which is .yml.</summary>
    private static readonly string[] Extensions =
        [".cs", ".ts", ".tsx", ".css", ".ps1", ".yml", ".yaml"];

    /// <summary>
    /// Pruned whole rather than filtered per file: node_modules alone holds tens
    /// of thousands of .ts files, none of them ours. `local` is the maintainer's
    /// git-ignored scratch area and is not part of the published repository, and
    /// `wwwroot` is where the frontend's production build is copied for the Host
    /// to serve — git-ignored, regenerated by `npm run build`, and hand-editing
    /// it would be overwritten by the next one. Every name here is either build
    /// output or not in the repository at all.
    /// </summary>
    private static readonly string[] SkippedDirectories =
        ["bin", "obj", "node_modules", "dist", "coverage", "TestResults",
         ".git", ".vs", ".idea", ".claude", "Migrations", "local", "wwwroot"];

    private static readonly Regex Copyright =
        new(@"Copyright \(c\) \d{4} The DealerFOSS contributors\.", RegexOptions.Compiled);

    /// <summary>How far in the five markers must appear. The longest real header
    /// in the repository is 66 lines; this leaves room without reading whole files.</summary>
    private const int HeaderLines = 200;

    private static string RepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "DealerFOSS.slnx")))
        {
            directory = directory.Parent;
        }

        directory.Should().NotBeNull(
            because: "the tests run from inside the repository, which DealerFOSS.slnx identifies");

        return directory!.FullName;
    }

    private static IEnumerable<string> SourceFiles(string root)
    {
        var pending = new Stack<string>();
        pending.Push(root);

        while (pending.Count > 0)
        {
            var current = pending.Pop();

            foreach (var child in Directory.EnumerateDirectories(current))
            {
                if (!SkippedDirectories.Contains(Path.GetFileName(child), StringComparer.OrdinalIgnoreCase))
                {
                    pending.Push(child);
                }
            }

            foreach (var file in Directory.EnumerateFiles(current))
            {
                if (Extensions.Contains(Path.GetExtension(file), StringComparer.OrdinalIgnoreCase))
                {
                    yield return file;
                }
            }
        }
    }

    /// <summary>
    /// Strips whatever a language uses to open a comment, so one rule covers
    /// `//`, `#` and `/* … */` without knowing which file it is looking at.
    /// </summary>
    private static string WithoutCommentLeader(string line) =>
        line.TrimStart().TrimStart('/', '#', '*').TrimStart();

    private static List<string> MissingParts(string path)
    {
        var lines = File.ReadLines(path).Take(HeaderLines).ToList();
        var header = string.Join('\n', lines);
        var missing = new List<string>();

        if (!Copyright.IsMatch(header))
        {
            missing.Add("the copyright line");
        }

        if (!header.Contains("SPDX-License-Identifier: AGPL-3.0-or-later", StringComparison.Ordinal))
        {
            missing.Add("SPDX-License-Identifier");
        }

        if (!header.Contains("Overview: Purpose, File Design, and Engineering", StringComparison.Ordinal))
        {
            missing.Add("Overview:");
        }

        if (!Opens(lines, "Usage:"))
        {
            missing.Add("Usage:");
        }

        if (!Opens(lines, "Coding Instructions:"))
        {
            missing.Add("Coding Instructions:");
        }

        return missing;
    }

    /// <summary>
    /// A section is a line that STARTS with the name once the comment leader is
    /// gone — not a mention of it in prose, which is why this is not a substring
    /// search over the whole header.
    /// </summary>
    private static bool Opens(IEnumerable<string> lines, string section) =>
        lines.Any(line => WithoutCommentLeader(line).StartsWith(section, StringComparison.Ordinal));

    [Fact]
    public void Every_hand_written_source_file_opens_with_the_four_part_header()
    {
        var root = RepositoryRoot();

        var checkedFiles = 0;
        var offenders = new List<string>();

        foreach (var file in SourceFiles(root))
        {
            checkedFiles++;

            var missing = MissingParts(file);
            if (missing.Count > 0)
            {
                var relative = Path.GetRelativePath(root, file).Replace('\\', '/');
                offenders.Add($"{relative} — missing {string.Join(", ", missing)}");
            }
        }

        checkedFiles.Should().BeGreaterThan(300,
            because: "the repository held 379 of these on 2026-09-14, and a walk that finds " +
                     "almost none has lost the repository root rather than found a tidy tree");

        offenders.Should().BeEmpty(
            because: "doc 08 §5 requires the header on every hand-written source file, and a " +
                     "reader who cannot tell what a file is for from its first screen has to " +
                     "read the whole thing to find out");
    }
}
